package ViewJanelas;

/**
 *
 * @author José Armando
 */
public class JanelaDevolucao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JanelaDevolucao.class.getName());

    /**
     * Creates new form JanelaDevolucao
     */
    public JanelaDevolucao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID do Empréstimo:");

        jLabel2.setText("ID da Multa:");

        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jButton1.setText("Registrar Devolução");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Quitar/Pagar Multa");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton1))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addComponent(jTextField1)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            try {
            // CORRIGIDO: Agora usa o jTextField1
            String idStr = jTextField1.getText().trim(); 
            if (idStr.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Digite o ID do Empréstimo!");
                return;
            }
            int idEmprestimo = Integer.parseInt(idStr);

            // 1. Busca o empréstimo no banco 
            modelo.dao.EmprestimoDAO emprestimoDAO = new modelo.dao.EmprestimoDAO();
            modelo.Emprestimo emp = emprestimoDAO.buscarPorId(idEmprestimo);

            if (emp == null || emp.getSituacao().equals("Devolvido")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Empréstimo não encontrado ou já devolvido!");
                return;
            }

            // 2. O Controle faz a mágica: finaliza o empréstimo, devolve o livro pro estoque e GERA A MULTA se atrasou
            controle.EmprestimoControle controleEmp = new controle.EmprestimoControle();
            String resultado = controleEmp.realizarDevolucao(emp, idEmprestimo);

            // 3. Mostra na tela se deu certo e se gerou multa!
            javax.swing.JOptionPane.showMessageDialog(this, resultado, "Aviso de Devolução", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            // CORRIGIDO: Agora limpa o jTextField1
            jTextField1.setText(""); 

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // CORRIGIDO: Agora usa o jTextField2
            String idMultaStr = jTextField2.getText().trim(); 
            if (idMultaStr.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Digite o ID da Multa para pagar!");
                return;
            }
            int idMulta = Integer.parseInt(idMultaStr);

            // Chama o DAO para dar baixa na multa no banco de dados
            modelo.dao.MultaDAO multaDAO = new modelo.dao.MultaDAO();
            boolean sucesso = multaDAO.quitarMulta(idMulta);

            if (sucesso) {
                javax.swing.JOptionPane.showMessageDialog(this, "Multa paga e quitada com sucesso!");
                
                // CORRIGIDO: Agora limpa o jTextField2
                jTextField2.setText(""); 
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao tentar quitar a multa. Verifique o ID.");
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JanelaDevolucao().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
