/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewJanelas;

/**
 *
 * @author José Armando
 */
public class JanelaReserva extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JanelaReserva.class.getName());

    /**
     * Creates new form JanelaReserva
     */
    public JanelaReserva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Matrícula do Usuario:");

        jLabel2.setText("ID do Livro:");

        jButton1.setText("Fazer Reserva");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jTextField2))
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
            // Pega o que foi digitado nas caixas de texto
            String matricula = jTextField1.getText().trim(); 
            String idLivroStr = jTextField2.getText().trim(); 

            if (matricula.isEmpty() || idLivroStr.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, preencha a Matrícula e o ID do Livro!");
                return;
            }

            int idLivro = Integer.parseInt(idLivroStr);

            // 1. Busca no banco de dados para ver se existem
            modelo.dao.UsuarioDAO usuarioDAO = new modelo.dao.UsuarioDAO();
            modelo.dao.LivroDAO livroDAO = new modelo.dao.LivroDAO();

            modelo.Usuario usuario = usuarioDAO.buscarPorMatricula(matricula);
            modelo.Livro livro = livroDAO.buscarPorId(idLivro);

            if (usuario == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Usuário não encontrado no banco de dados!");
                return;
            }
            if (livro == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Livro não encontrado no banco de dados!");
                return;
            }

            // 2. Trava de segurança do UML: Só reserva se NÃO tiver livro no estoque
            if (livro.getQuantidadeDisponivel() > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "O livro tem " + livro.getQuantidadeDisponivel() + " cópia(s) disponível(is). Faça um Empréstimo direto!");
                return;
            }

            // 3. Cria a reserva e salva no banco
            modelo.Reserva novaReserva = new modelo.Reserva(usuario, livro);
            modelo.dao.ReservaDAO reservaDAO = new modelo.dao.ReservaDAO();

            boolean sucesso = reservaDAO.adicionar(novaReserva);

            if (sucesso) {
                javax.swing.JOptionPane.showMessageDialog(this, "Reserva feita com sucesso!\nO livro ficará reservado até: " + novaReserva.getDataExpiracao(), "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
                // Limpa as caixinhas para a próxima reserva
                jTextField1.setText("");
                jTextField2.setText("");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar a reserva no banco de dados.");
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "O ID do livro deve ser apenas números!");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JanelaReserva().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
